#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Copying 'initial' to 0"
cp -r initial 0

# remove `.orig` extensions where applicable
find 0 -name "*.orig" -exec bash -c 'cp "$0" "${0%.orig}"' {} \;

# If liggghts in installed, run the DEM model
if (command -v updateMesh > /dev/null); then
    echo "blastAMR is available: (init not implemented)"
    # (cd DEM_small && ./Allrun)
else
    echo "blastAMR not found in the PATH: skipping"
fi

runApplication blockMesh
# runApplication setSolidFraction -compressible -alpha.phase1 "alpha.metal1" -alpha.phase2 "alpha.air" -subDivisions 6
runApplication setFields
# runApplication transformPoints -rotate '((0 1 0) (0 0 1))'
# runApplication compressibleLaserbeamFoam

compressibleLaserbeamFoam 2>&1 | tee log.compressibleLaserbeamFoam